# Generated by Django 3.2.15 on 2023-07-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(default=None, max_length=50, null=True)),
                ('r_code', models.CharField(default=None, max_length=100, null=True)),
                ('createdDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.roles')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
