# Generated by Django 3.2.15 on 2023-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20230703_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('it_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_type', models.CharField(blank=True, max_length=255, null=True)),
                ('createdDate', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'item_type',
            },
        ),
    ]
