# Generated by Django 3.2.15 on 2023-07-04 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_itemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddShop',
            fields=[
                ('as_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_name', models.CharField(blank=True, max_length=255, null=True)),
                ('as_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('as_gst_num', models.CharField(blank=True, max_length=255, null=True)),
                ('as_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('as_item_price', models.CharField(blank=True, max_length=255, null=True)),
                ('as_item_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('as_item_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('as_item_img', models.CharField(blank=True, max_length=255, null=True)),
                ('it_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.itemtype')),
            ],
            options={
                'db_table': 'add_shop',
            },
        ),
    ]
