# Generated by Django 3.2.15 on 2023-07-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_addshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='addshop',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.users'),
            preserve_default=False,
        ),
    ]
