# Generated by Django 3.2.15 on 2023-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_addshop_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='u_profile_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
