# Generated by Django 3.2.15 on 2023-07-05 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_users_u_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addshop',
            old_name='as_item_desc',
            new_name='as_shop_img',
        ),
        migrations.RemoveField(
            model_name='addshop',
            name='as_item_img',
        ),
        migrations.RemoveField(
            model_name='addshop',
            name='as_item_name',
        ),
        migrations.RemoveField(
            model_name='addshop',
            name='as_item_price',
        ),
        migrations.RemoveField(
            model_name='addshop',
            name='as_item_qty',
        ),
        migrations.RemoveField(
            model_name='addshop',
            name='it_id',
        ),
        migrations.CreateModel(
            name='addItem',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_price', models.CharField(blank=True, max_length=255, null=True)),
                ('item_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('item_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('item_image', models.CharField(blank=True, max_length=255, null=True)),
                ('it_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.itemtype')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.users')),
                ('shop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.addshop')),
            ],
            options={
                'db_table': 'add_item',
            },
        ),
    ]
