# Generated by Django 3.2.15 on 2023-07-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20230705_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
