# Generated by Django 3.2.15 on 2023-07-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_additem_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='it_id',
        ),
        migrations.AddField(
            model_name='addshop',
            name='it_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.itemtype'),
            preserve_default=False,
        ),
    ]
