# Generated by Django 3.2.15 on 2023-07-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20230705_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('odr_id', models.AutoField(primary_key=True, serialize=False)),
                ('odr_category', models.CharField(blank=True, max_length=225, null=True)),
                ('odr_name', models.CharField(blank=True, max_length=225, null=True)),
                ('odr_date', models.DateTimeField(auto_now_add=True)),
                ('odr_amount', models.CharField(blank=True, max_length=225, null=True)),
                ('odr_igst', models.CharField(blank=True, max_length=225, null=True)),
                ('odr_cgst', models.CharField(blank=True, max_length=225, null=True)),
                ('odr_delivery_amount', models.CharField(blank=True, max_length=225, null=True)),
                ('odr_delivery_address', models.CharField(blank=True, max_length=225, null=True)),
                ('odr_status', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
