# Generated by Django 3.2.15 on 2023-07-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='u_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='delivery.users'),
            preserve_default=False,
        ),
    ]
